name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"     # chạy mỗi ngày 00:00 UTC
  workflow_dispatch:         # cho phép chạy tay

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ThaiNT960
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
